databases:
  - name: shortener_db
    databaseName: shortener_db
    user: shortener_user
    plan: free
    region: oregon

services:
  - type: redis
    name: shortener_cache
    plan: free
    region: oregon
    ipAllowList: []

  - type: web
    name: pranay-url-shortener
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /docs
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shortener_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: shortener_cache
          property: connectionString
      - key: BASE62
        value: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
      - key: SCRAMBLER_PRIME
        value: "2147483647"
      - key: SCRAMBLER_SECRET
        value: "1580030173"
      - key: MIN_LENGTH_OFFSET
        value: "1000000000"

  - type: worker
    name: url-shortener-sync-worker
    env: docker
    plan: free
    region: oregon
    dockerCommand: python service/sync.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shortener_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: shortener_cache
          property: connectionString
      - key: PYTHONPATH
        value: /app